// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW4iKEHO2a4__hLHr5f1HRy7kTzJ6vdJU',
    appId: '1:932806943365:web:b9a495a302d2907d1e7fec',
    messagingSenderId: '932806943365',
    projectId: 'ecommerce-f9217',
    authDomain: 'ecommerce-f9217.firebaseapp.com',
    storageBucket: 'ecommerce-f9217.appspot.com',
    measurementId: 'G-FGE3X4EWP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNKdx3C7xPUt8iIwpciIRtpaYrDug4OAk',
    appId: '1:932806943365:android:142624c9eb0d797d1e7fec',
    messagingSenderId: '932806943365',
    projectId: 'ecommerce-f9217',
    storageBucket: 'ecommerce-f9217.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAYyiwkbM9eQc5VpxCXOymJR9bRUIrh8Y',
    appId: '1:932806943365:ios:8c4e91074b109c0b1e7fec',
    messagingSenderId: '932806943365',
    projectId: 'ecommerce-f9217',
    storageBucket: 'ecommerce-f9217.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAYyiwkbM9eQc5VpxCXOymJR9bRUIrh8Y',
    appId: '1:932806943365:ios:c968707d5780769b1e7fec',
    messagingSenderId: '932806943365',
    projectId: 'ecommerce-f9217',
    storageBucket: 'ecommerce-f9217.appspot.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
